<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Convention;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ConventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConventionRepository extends \Doctrine\ORM\EntityRepository
{


}
