<?php

namespace AppBundle\Repository;

/**
 * partenaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class partenaireRepository extends \Doctrine\ORM\EntityRepository
{

}
